### ISSUE TITLE
set action changing current Route to another one

### ISSUE THREAD

**Issue by Tuguldur007** [pbeshai/use-query-params#131] opened 2020-10-16 11:16 UTC
This is example I created and I am using fresh project created by create-react-app 
And all code is from official Documentations. 

Issue is when i go to /tacos/bus route and click change button for setting parameters, /tacos/bus route changed to /?foo=0.012312&x=0.1312 something or /tacos?foo=... 

Please help ;) thank you guys for this nice npm project

The Code is. 

[Source.txt](https://github.com/pbeshai/use-query-params/files/5391126/Source.txt)

**Comment by pbeshai** [comment] 2020-10-16 15:45
Sorry, you need to provide more code for me to be able to figure this out. If you can create a working code sandbox that demonstrates the problem I'd be happy to take a look. Be sure to have the QueryParamProvider set up properly:

```js
  <Router>
    <QueryParamProvider
      ReactRouterRoute={Route}
    >
      <App />
    </QueryParamProvider>
  </Router>
```

You can see an example here: https://github.com/pbeshai/use-query-params/tree/master/examples/react-router

Note this lib doesn't currently work with React Router v6 #108

**Comment by utkarsh22garg** [comment] 2022-03-14 18:25
Hi  @pbeshai,

I am also facing the exact issue when integrating react-router v6 with use-query-params. I have created a codesandbox to reproduce this issue. ([Codesandbox demo](https://codesandbox.io/s/exciting-jennings-3ospdg?file=/src/App.js)). In this demo I have used the RouteAdapter as shared by you here https://github.com/pbeshai/use-query-params/issues/108#issuecomment-785209454

I am a huge fan of this repository. However, with recent upgrade of react-router v6 I am unable to use this properly. It would be great if you can suggest a fix for this and possibly can release them so that other devs do not need to repeat writing the adapter.

Thanks in advance.

**Comment by PEsteves8** [comment] 2022-03-16 17:27
I have a similar issue. From what I can see the adapter provided here as an issue: https://github.com/pbeshai/use-query-params/issues/108#issuecomment-1029329429

The location object inside the `push` and `replace` functions is not the current `location` when `setQuery` gets called on mount.

If you compare the `location.pathname` coming from the `useLocation` hook call and the one inside the push call, they'll be different (again if `setQuery` gets called on mount).

One thing that seems to fix it, is removing the local arg for the `location` and using the one outside coming from the `useLocaton` hook updating the `useMemo` dependency array like so:

```
const RouteAdapter = ({ children }) => {
  const navigate = useNavigate();
  const location = useLocation();

  const adaptedHistory = React.useMemo(
    () => ({
      replace() {
        navigate(location, { replace: true, state: location.state });
      },
      push(location) {
        navigate(, { replace: false, state: location.state });
      },
    }),
    [navigate, location]
  );
  return children({ history: adaptedHistory, location });
};
```

But I get the impression that that may increase the number of unnecessary renders and cause performance issues (I'm not noticing that though).

**Comment by PEsteves8** [comment] 2022-03-16 17:35
It seems that there's an issue in the adapter provided here: https://github.com/pbeshai/use-query-params/issues/108#issuecomment-1029329429

The location returned from the `useLocation` call, will always be the new location, whereas the one inside the `push` call will be the previous location *if* `setQuery` gets called on mount. It seems to be a sync issue. 

I've only been able to fix this by using state to check whether the component has mounted before calling `setQuery` in the `useEffect` function, which serves the purpose of my specific use case.

**Comment by pratheekbhandary** [comment] 2022-05-26 11:01
> Hi @pbeshai,
> 
> I am also facing the exact issue when integrating react-router v6 with use-query-params. I have created a codesandbox to reproduce this issue. ([Codesandbox demo](https://codesandbox.io/s/exciting-jennings-3ospdg?file=/src/App.js)). In this demo I have used the RouteAdapter as shared by you here [#108 (comment)](https://github.com/pbeshai/use-query-params/issues/108#issuecomment-785209454)
> 
> How to reproduce the issue:
> 
> 1. Visit demo.
> 2. Click on About link.
> 3. Now click on Dashboard link. On clicking dashboard link it should have appended activeId='testing' to `/dashboard` but it changes the route to last visited link and append query param to it, i.e., it will become `/about?activeId=testing` in this case. In ideal scenario it should have become `/dashboard?activeId=testing`.
> 
> I am a huge fan of this repository. However, with recent upgrade of react-router v6 I am unable to use this properly. It would be great if you can suggest a fix for this and possibly can release them so that other devs do not need to repeat writing the adapter.
> 
> Thanks in advance.

Hi @utkarsh22garg,
Even I ran into similar problem. But this suggestion > https://github.com/pbeshai/use-query-params/issues/108#issuecomment-1120301036 works for me. I have modified your [sandbox](https://codesandbox.io/s/modest-https-m3zp1s?file=/src/App.js) with suggested changes. I'm curious to know how you fixed this issue? 
Thanks in advance.

**Comment by utkarsh22garg** [comment] 2022-05-26 11:10
Thanks @pratheekbhandary , the sandbox provided by you works. Passing only `search` param works.

**Closed** 2022-06-25 18:31 UTC
